#!/bin/bash
#
#/ Boot a vagrant box and provision it using the current project.
#/ If no project exists, it will be created.
#
if [ "$1" = "-h" -o "$1" = "--help" -o "$1" = "help" ]; then
  grep '^#/' <"$0" | cut -c4-
  exit 0;
fi

set -e
set -u

script_dir="$(cd "$(dirname "$BASH_SOURCE")" && pwd)"

$script_dir/build

. $script_dir/lib/env

cd $project_dir

if [ -n "$(bin/vagrant status | grep ^default | grep running)" ]; then
  echo "Vagrant is running." >&2
else
  bin/vagrant up
fi

exit 0
