#!/bin/bash
set -e
set -u

script_dir="$(cd "$(dirname "$BASH_SOURCE")" && pwd)"

. $script_dir/lib/env

[ -f "$project_dir/.vagrant" ] && (cd "$project_dir" && bin/vagrant destroy -f)
[ -d "$project_dir" ] && rm -rf "$project_dir"
[ -d "$project_repo_dir" ] && rm -rf "$project_repo_dir"
[ -d "$database_repo_dir" ] && rm -rf "$database_repo_dir"
[ -L "$config_dir" ] && rm -f "$config_dir"

exit 0
