#!/bin/bash
set -e
set -u

script_dir="$(cd "$(dirname "$BASH_SOURCE")" && pwd)"

$script_dir/boot

. $script_dir/lib/env

cd $project_dir

# For some reason vagrant hangs unless we exit. But, it does return the exit
# status for us, which results in this script's exit status.
bin/vagrant ssh -c '/home/vagrant/run-tests; exit $?'
